// Counter
export const INCREMENT_ONE: String = "INCREMENT_ONE";
export const DECREMENT_ONE: String = "DECREMENT_ONE";
export const SET_ZERO: String = "SET_ZERO";

// Scores
export const SET_SCORES_LOADING_TRUE: String = "SET_SCORES_LOADING_TRUE";
export const SET_SCORES_LOADING_FALSE: String = "SET_SCORES_LOADING_FALSE";
export const GET_LOWEST_SCORES: String = "GET_LOWEST_SCORES";
export const SET_LOWEST_SCORES_ERROR_TRUE: String =
  "SET_LOWEST_SCORES_ERROR_TRUE";
export const SET_LOWEST_SCORES_ERROR_FALSE: String =
  "SET_LOWEST_SCORES_ERROR_FALSE";
export const GET_HIGHEST_SCORES: String = "GET_HIGHEST_SCORES";
export const SET_HIGHEST_SCORES_ERROR_TRUE: String =
  "SET_HIGHEST_SCORES_ERROR_TRUE";
export const SET_HIGHEST_SCORES_ERROR_FALSE: String =
  "SET_HIGHEST_SCORES_ERROR_FALSE";
